config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  namespace :admin do
    resources :users
  end

  resources :hubs, id: /.*/, only: [:index, :show] do
    get :website_overview
    get :api_overview
    get :bws_overview
    get :item_count
    get :metadata_completeness
    get :wikimedia_overview

    resources :contributors, id: /.*/, only: [:index, :show] do
      get :contributor_website_overview
      get :contributor_api_overview
      get :contributor_bws_overview
      get :contributor_item_count
      get :contributor_metadata_completeness
      get :contributor_wikimedia_overview
      resources :events, only: [:show]
      resources :locations, only: [:index]
      resources :timelines, only: [:show]
      resources :wikimedia_preparations, only: [:index]
    end
    resources :events, only: [:show]
    resources :locations, only: [:index]
    resources :timelines, only: [:show]
    resources :wikimedia_preparations, only: [:index]
  end

  resources :search_terms, only: [:show]

  get :api_events, controller: :events
  get :website_events, controller: :events
  get :bws_events, controller: :events
  get :api_search_terms, controller: :search_terms
  get :website_search_terms, controller: :search_terms
  get :contributor_comparison, controller: :contributors

  root 'hubs#index'
end

app/views/shared/_api_use_metrics.html.erb
<%# Local variables: @api_overview [OverviewApi] %>

<% if api_data_for_date_range? %>

  <table>
    <tr>
      <td>
        <div class="tooltip">
          View item metadata
          <span class="tooltiptext"><%= view_api_item_tooltip %></span>
        </div>
      </td>
      <td><%= @api_overview.events %></td>
    </tr>
  </table>

<% else %>
    <div class="no-data">Data not available for this date range.</div>
<% end %>

app/views/shared/_bws_use_metrics.html.erb
<%# Local variables: @bws_overiew [BwsOverview],
                     @bws_event_totals [BwsEventTotals] %>
<% if bws_data_for_date_range? %>

  <table>
    <tr>
      <td>
          <div class="tooltip">
            Item count
            <span class="tooltiptext"><%= bws_item_count_tooltip %></span>
          </div>
      </td>
      <td>
        <%= number_with_delimiter(@bws_item_count, :delimiter => ',') %>
      </td>
    </tr>
    <tr>
      <td>
          <div class="tooltip">
            Item views
            <span class="tooltiptext"><%= view_bws_item_tooltip %></span>
          </div>
      </td>
      <td>
        <%= number_with_delimiter(@bws_event_totals.item_events, :delimiter => ',') %>
      </td>
    </tr>
    <tr>
      <td>
        <div class="tooltip">
          Click throughs
          <span class="tooltiptext"><%= click_through_tooltip %></span>
        </div>
      </td>
      <td>
        <%= number_with_delimiter(@bws_event_totals.click_throughs, :delimiter => ',') %>
      </td>
    </tr>
    <tr>
      <td>
        <div class="tooltip">
          Users
          <span class="tooltiptext"><%= users_tooltip %></span>
        </div>
      </td>
      <td>
        <%= number_with_delimiter(@bws_overview.users, :delimiter => ',') %>
      </td>
    </tr>
    <tr>
      <td>
        <div class="tooltip">
          Sessions
          <span class="tooltiptext"><%= sessions_tooltip %></span>
        </div>
      </td>
      <td>
        <%= number_with_delimiter(@bws_overview.sessions, :delimiter => ',') %>
      </td>
    </tr>
  </table>

<% else %>
    <div class="no-data">Data not available for this date range.</div>
<% end %>

app/views/shared/_contributor_comparison.html.erb
<form class="comparison">
  <fieldset>
    <legend>DPLA Website</legend>
    <div>
      <input type="checkbox" id="website-view-input" name="column" 
             value="website-view" checked="checked"
             onclick="toggle_column(this)">
      <label for="website-view-input">dp.la Item Views</label>
    </div>
    <div>
      <input type="checkbox" id="click-through-input" name="column"
             value="click-through" checked="checked"
             onclick="toggle_column(this)">
      <label for="click-through-input">dp.la Click Throughs</label>
    </div>
    <div>
      <input type="checkbox" id="website-session-input" name="column" 
             value="website-session" checked="checked"
             onclick="toggle_column(this)">
      <label for="website-session-input">dp.la Sessions</label>
    </div>
    <div>
      <input type="checkbox" id="website-user-input" name="column"
             value="website-user" checked="checked"
             onclick="toggle_column(this)">
      <label for="website-user-input">dp.la Users</label>
    </div>
  </fieldset>

  <fieldset>
    <legend>Black Women's Suffrage</legend>
    <% if bws_data_for_date_range? %>
      <div>
        <input type="checkbox" id="bws-item-count-input" name="column" 
               value="bws-item-count" checked="checked"
               onclick="toggle_column(this)">
        <label for="bws-item-count-input">BWS Item Count</label>
      </div>
      <div>
        <input type="checkbox" id="bws-view-input" name="column" 
               value="bws-view" checked="checked"
               onclick="toggle_column(this)">
        <label for="bws-view-input">BWS Item Views</label>
      </div>
      <div>
        <input type="checkbox" id="bws-click-through-input" name="column"
               value="bws-click-through" checked="checked"
               onclick="toggle_column(this)">
        <label for="bws-click-through-input">BWS Click Throughs</label>
      </div>
      <div>
        <input type="checkbox" id="bws-session-input" name="column" 
               value="bws-session" checked="checked"
               onclick="toggle_column(this)">
        <label for="bws-session-input">BWS Sessions</label>
      </div>
      <div>
        <input type="checkbox" id="bws-user-input" name="column"
               value="bws-user" checked="checked"
               onclick="toggle_column(this)">
        <label for="bws-user-input">BWS Users</label>
      </div>
    <% else %>
      <div class="no-data">Data not available for this date range.</div>
    <% end %>
  </fieldset>

  <fieldset>
    <legend>DPLA API</legend>
    <% if api_data_for_date_range? %>
      <div>
        <input type="checkbox" id="api-view-input" name="column"
               value="api-view" checked="checked"
               onclick="toggle_column(this)">
        <label for="api-view-input">API Views</label>
      </div>
    <% else %>
      <div class="no-data">Data not available for this date range.</div>
    <% end %>
  </fieldset>

  <fieldset>
    <legend>Item count</legend>
    <div>
      <input type="checkbox" id="item-count-input" name="column"
               value="item-count" checked="checked"
               onclick="toggle_column(this)">
        <label for="item-count-input">Item count</label>
    </div>
  </fieldset>

  <fieldset>
    <legend>Wikimedia Integration</legend>
      <% WikimediaPreparationsPresenter.fields.each do |field| %>
      <div>
        <input type="checkbox" id="<%= field %>-input" name="column"
               value="<%= field %>" checked="checked"
               onclick="toggle_column(this)">
        <label for="<%= field %>-input"><%= field.titleize %></label>
      </div>
    <% end %>
  </fieldset>

  <fieldset>
    <legend>Metadata Completeness</legend>
    <% MetadataCompletenessPresenter.fields.each do |field| %>
      <% unless field == 'count' %>
        <div>
          <input type="checkbox" id="<%= field %>-input" name="column"
                 value="<%= field %>" checked="checked"
                 onclick="toggle_column(this)">
          <label for="<%= field %>-input"><%= field.titleize %></label>
        </div>
      <% end %>
    <% end %>
  </fieldset>
</form>

<div class='download'>
  <%= link_to 'Download CSV', controller: :contributors,
                              action: params[:action],
                              hub_id: params[:hub_id],
                              start_date: current_start_date,
                              end_date: current_end_date,
                              format: :csv %>
</div>

<table id='comparison'>
  <thead>
    <tr>
      <th>Contributor</th>
      <th class="website-view">dp.la Item Views</th>
      <th class="click-through">dp.la Click Throughs</th>
      <th class="website-session">dp.la Sessions</th>
      <th class="website-user">dp.la Users</th>
      <% if bws_data_for_date_range? %>
        <th class="bws-item-count">BWS Item Count</th>
        <th class="bws-view">BWS Item Views</th>
        <th class="bws-click-through">BWS Click Throughs</th>
        <th class="bws-session">BWS Sessions</th>
        <th class="bws-user">BWS Users</th>
      <% end %>
      <% if api_data_for_date_range? %>
        <th class="api-view">API Views</th>
      <% end %>
      <th class="item-count">Item Count</th>
      <% WikimediaPreparationsPresenter.fields.each do |field| %>
        <th class="<%= field %>"><%= field.titleize %></th>
      <% end %>
      <% MetadataCompletenessPresenter.fields.each do |field| %>
        <% unless field == 'count' %>
          <th class="<%= field %>"><%= field.titleize %> Completeness</th>
        <% end %>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @contributor_comparison.totals.each do |contributor, totals| %>
      <tr>
        <td>
          <%= link_to contributor, controller: :contributors, action: :show,
                                   hub_id: params[:hub_id], id: contributor,
                                   start_date: current_start_date,
                                   end_date: current_end_date %>
        </td>
        <td class="website-view">
          <%= totals["Website"]["Views"] %>
        </td>
        <td class="click-through">
          <%= totals["Website"]["Click Throughs"] %>
        </td>
        <td class="website-session">
          <%= totals["Website"]["Sessions"] %>
        </td>
        <td class="website-user">
          <%= totals["Website"]["Users"] %>
        </td>
        <% if bws_data_for_date_range? %>
          <td class="bws-item-count">
            <%= totals["BWS"]["ItemCount"] %>
          </td>
          <td class="bws-view">
            <%= totals["BWS"]["Views"] %>
          </td>
          <td class="bws-click-through">
            <%= totals["BWS"]["Click Throughs"] %>
          </td>
          <td class="bws-session">
            <%= totals["BWS"]["Sessions"] %>
          </td>
          <td class="bws-user">
            <%= totals["BWS"]["Users"] %>
          </td>
        <% end %>
        <% if api_data_for_date_range? %>
          <td class="api-view">
            <%= totals["Api"]["Views"] %>
          </td>
        <% end %>
        <td class="item-count">
          <%= totals["ItemCount"] %>
        </td>
        <% WikimediaPreparationsPresenter.fields.each do |field| %>
          <% value = totals["WikimediaIntegration"][field] %>
          <td class="<%= field %> <%= percentage_class(value) %>">
            <%= render_percentage(value) %>
          </td>
        <% end %>
        <% MetadataCompletenessPresenter.fields.each do |field| %>
          <% unless field == "count" %>
            <% value = totals["MetadataCompleteness"][field] %>
            <td class="<%= field %> <%= percentage_class(value) %>">
              <%= render_percentage(value) %>
            </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_data_menu.html.erb
<%# Local variables: target [Hub|Contributor] %>

<div class="data-menu">
  <ul>
    <li>
      <%= render_overview_link(target) %>
    </li>
    <li> 
      <%= render_website_timelines_link(target) %>
    </li>
    <li> 
      <%= render_api_timelines_link(target) %>
    </li>
    <li> 
      <%= render_locations_link(target) %>
    </li>
    <li>
      <%= render_view_item_link(target) %>
    </li>
    <li>
      <%= render_view_exhibit_link(target) %>
    </li>
    <li>
      <%= render_view_pss_link(target) %>
    </li>
    <li>
      <%= render_click_through_link(target) %>
    </li>
    <li>
      <%= render_view_api_link(target) %>
    </li>
    <li>
      <%= render_wikimedia_readiness_link(target) %>
    </li>
  </ul>
</div>

app/views/shared/_events_table.html.erb
<div class="item-table">
  <h2><%= @events.label %></h2>

  <div class="description-text">
    <%= find_tooltip(params[:event_id]) %>
  </div>

  <% if @events.rows.count > 0 %>

  <div class="result-info">
    Showing <%= @events.start_index %>-<%= @events.end_index %> of 
    <%= @events.total_results %> items.
  </div>

  <div class="download">
    <%= link_to "Download all #{@events.total_results} items",
                controller: :events,
                action: params[:action],
                start_date: current_start_date,
                end_date: current_end_date,
                hub_id: params[:hub_id],
                contributor_id: params[:contributor_id],
                event_id: params[:event_id],
                format: :csv %>
  </div>

  <table>
    <tr>
      <th>Item</th>
      <% unless @contributor %>
        <th>Contributor</th>
      <% end %>
      <th><%= @events.action %></th>
    </tr>
    <% @events.rows.each do |row| %>
    <tr>
      <td>
        <a href="<%= "#{Settings.dpla.base_uri}item/#{@events.id(row)}" %>">
          <%= @events.title(row) %>
        </a>
      </td>
      <% unless @contributor %>
      <td><%= @events.contributor(row) %></td>
      <% end %>
      <td><%= @events.count(row) %></td>
    </tr>
    <% end %>
  </table>
  <% else %>
    No activity to report from this time period.
  <% end %>
</div>

app/views/shared/_frontend_use_metrics.html.erb
<%# Local variables: @website_overiew [WebsiteOverview],
                     @website_event_totals [WebsiteEventTotals] %>

<table>
  <tr>
    <td>
        <div class="tooltip">
          Item views
          <span class="tooltiptext"><%= view_item_tooltip %></span>
        </div>
    </td>
    <td>
      <%= number_with_delimiter(@website_event_totals.view_events, :delimiter => ',') %>
    </td>
  </tr>
  <tr class="subitem">
    <td>
      <div class="tooltip">
        Digital library catalog
        <span class="tooltiptext"><%= view_metadata_record_tooltip %></span>
      </div>
    </td>
    <td>
      <%= number_with_delimiter(@website_event_totals.item_events, :delimiter => ',') %>
    </td>
  </tr>
  <tr class="subitem">
    <td>
      <div class="tooltip">
        Exhibition
        <span class="tooltiptext"><%= view_exhibition_tooltip %></span>
      </div>
    </td>
    <td>
      <%= number_with_delimiter(@website_event_totals.exhibit_events, :delimiter => ',') %>
    </td>
  </tr>
  <tr class="subitem">
    <td>
      <div class="tooltip">
        Primary source set
        <span class="tooltiptext"><%= view_primary_source_set_tooltip %></span>
      </div>
    </td>
    <td>
      <%= number_with_delimiter(@website_event_totals.pss_events, :delimiter => ',') %>
    </td>
  </tr>
  <tr>
    <td>
      <div class="tooltip">
        Click throughs
        <span class="tooltiptext"><%= click_through_tooltip %></span>
      </div>
    </td>
    <td>
      <%= number_with_delimiter(@website_event_totals.click_throughs, :delimiter => ',') %>
    </td>
  </tr>
  <tr>
    <td>
      <div class="tooltip">
        Users
        <span class="tooltiptext"><%= users_tooltip %></span>
      </div>
    </td>
    <td>
      <%= number_with_delimiter(@website_overview.users, :delimiter => ',') %>
    </td>
  </tr>
  <tr>
    <td>
      <div class="tooltip">
        Sessions
        <span class="tooltiptext"><%= sessions_tooltip %></span>
      </div>
    </td>
    <td>
      <%= number_with_delimiter(@website_overview.sessions, :delimiter => ',') %>
    </td>
  </tr>
</table>

app/views/shared/_header.html.erb
<div>
  <%= image_tag("/assets/dpla-logo-black.jpg", alt: "DPLA") %>
  <span>Analytics Dashboard</span>
</div>

app/views/shared/_map.html.erb
<%# Local variables: ga_token [String] google analytics authentication token
                     hub [String] hub name
                     contributor [String] contributor name (optional) %>
      
<!-- Data for google analytics javascript embed api -->
<div id="access-token" data-access-token="<%= ga_token %>" />
<div id="profile-id" data-profile-id="<%= Settings.google_analytics.frontend_profile_id %>" />
<div id="hub" data-hub="<%= hub %>" />
<% contributor ||= "" %>
<div id="contributor" data-contributor="<%= contributor %>" />
<div id="start-date" data-start-date="<%= @start_date.iso8601 %>" />
<div id="end-date" data-end-date="<%= @end_date.iso8601 %>" />


<h2>DPLA website user locations</h2>

<div class="description-text">
  This feature is no longer available due to new security protocols. It may be restored in the future.
</div>

<% if false %>

<div class="description-text"><%= user_location_tooltip %></div> 

<br/>

<h3>United States</h3>
<section id="us-map">
  If map does not load after a few seconds, try refreshing the page.
</section>
<h3>World</h3>
<section id="world-map">
  If map does not load after a few seconds, try refreshing the page.
</section> 

<% end %>

app/views/shared/_navigation.html.erb
<nav>
  <ul>
    <% if current_user.hub == "All" %>
        <li>
          <%= link_to "Hubs", hubs_path(date_opts) %>
        </li>
    <% else %>
        <li>
          <%= link_to "Overview", hub_path(current_user.hub, date_opts) %>
        </li>
        <% @hub ||= Hub.new(current_user.hub, "", "") %>
        <% if @hub.contributors.count > 1 %>
          <li>
            <%= link_to "Contributors",
                hub_contributors_path(current_user.hub, date_opts) %>
          </li>
        <% end %>
    <% end %>
    <li>
      <%= link_to "Search Terms", search_term_path("website", date_opts) %>
    </li>
  </ul>
  <span class="divider">|</span>
  <ul>
    <% if current_user.admin? %>
        <li>
          <%= link_to "Users", admin_users_path %>
        </li>
    <% end %>
    <li>
      <%= link_to "My account", admin_user_path(current_user) %>
    </li>
    <li>
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    </li>
  </ul>
</nav>

app/views/shared/_timeline.html.erb
<%# Local variables: ga_token [String] google analytics authentication token
                     hub [String] hub name
                     contributor [String] contributor name (optional) %>
      
<!-- Data for google analytics javascript embed api -->
<div id="access-token" data-access-token="<%= ga_token %>" />
<div id="profile-id" data-profile-id="<%= Settings.google_analytics.frontend_profile_id %>" />
<div id="hub" data-hub="<%= hub %>" />
<% contributor ||= "" %>
<div id="contributor" data-contributor="<%= contributor %>" />
<div id="start-date" data-start-date="<%= @start_date.iso8601 %>" />
<div id="end-date" data-end-date="<%= @end_date.iso8601 %>" />


<h2><%= @id.titlecase %> usage timelines</h2>

<div class="description-text"><%= timelines_tooltip %></div>

<br/>

<h3>Item views</h3>
<div class="description-text"><%= view_item_tooltip %></div>
<section id="item-view-timeline">
  If timeline does not load after a few seconds, try refreshing the page.
</section>

<h3>Click throughs</h3>
<div class="description-text"><%= click_through_tooltip %></div>
<section id="click-through-timeline">
  If timeline does not load after a few seconds, try refreshing the page.
</section>

<h3>Users</h3>
<div class="description-text"><%= users_tooltip %></div>
<section id="user-timeline">
  If timeline does not load after a few seconds, try refreshing the page.
</section>

<h3>Sessions</h3>
<div class="description-text"><%= sessions_tooltip %></div>
<section id="session-timeline">
  If timeline does not load after a few seconds, try refreshing the page.
</section>

app/views/shared/_timeline_api.html.erb
<%# Local variables: ga_token [String] google analytics authentication token
                     hub [String] hub name
                     contributor [String] contributor name (optional) %>
      
<!-- Data for google analytics javascript embed api -->
<div id="access-token" data-access-token="<%= ga_token %>" />
<div id="profile-id" data-profile-id="<%= Settings.google_analytics.api_profile_id %>" />
<div id="hub" data-hub="<%= hub %>" />
<% contributor ||= "" %>
<div id="contributor" data-contributor="<%= contributor %>" />
<div id="start-date" data-start-date="<%= @start_date.iso8601 %>" />
<div id="end-date" data-end-date="<%= @end_date.iso8601 %>" />
<div id="segment" data-segment="<%= Settings.google_analytics.api_segment %>" />


<h2>API use timelines</h2>

<div class="description-text">
  This feature is no longer available due to new security protocols. It may be restored in the future.
</div>

<% if false %>

<div class="description-text">
  <%= api_use_tooltip %>
  <%= timelines_tooltip %>
  API usage data is not available before May 2018.
</div>

<br/>

<h3>Item metadata views</h3>
<div class="description-text"><%= view_api_item_tooltip %></div>
<section id="api-item-view-timeline">
  If timeline does not load after a few seconds, try refreshing the page.
</section>

<% end %>

app/views/shared/_use_metrics.html.erb
<%# Local variables: target [Hub|Contributor] %>

<h2>Use Metrics</h2>

<ul>
  <li>Total events: <%= target.total_events %></li>
    <ul>
      <li>View item: <%= target.total_item_events %></li>
      <li>View exhibition item: <%= target.total_exhibit_events %></li>
      <li>View primary source: <%= target.total_pss_events %></li>
      <li>Click through: <%= target.total_click_throughs %></li>
    </ul>
  <li>Unique events: <%= target.unique_events %></li>
  <li>Sessions: <%= target.sessions %></li>
  <li>Users: <%= target.users %></li>
</ul>

app/views/shared/_wikimedia_overview.html.erb
<%# Local variables: @wp_data[Hash] @target[Hub|Contributor] %>

<% if @wa_data.present? %>

  <table>
    <% WikimediaAnalyticsPresenter.fields.each do |key| %>
      <% value = @wa_data[key] %>
      <% if value.present? %>
        <tr>
          <td>
            <div class="tooltip">
              <span><%= key.titleize %></span>
              <span class="tooltiptext"><%= find_tooltip(key) %></span>
            </div>
          </td>
          <td>
            <%= number_with_delimiter(value, :delimiter => ',') %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>

<% else %>
  <div class="no-data">Wikimedia upload and page view data not available</div>
<% end %>

<% key = 'wikimediaReady' %>

<% if @wp_data.present? && @wp_data.key?(key) %>
  <% value = @wp_data[key] %>

  <table>
    <% if WikimediaPreparationsPresenter.fields.include?(key) %>
      <tr>
        <td>
          <div class="tooltip">
            <span><%= key.titleize %></span>
            <span class="tooltiptext"><%= wikimedia_readiness_tooltip %></span>
          </div>
        </td>
        <td class="bar <%= percentage_class(value) %>">
          <%= render_percentage(value) %>
        </td>
      </tr>
    <% end %>
  </table>

<% else %>
  <div class="no-data">Wikimedia readiness data not available</div>
<% end %>

<% keys = WikimediaAnalyticsPresenter.fields %>

<br/>

<p>More data about <%= render_wikimedia_readiness_link(@target) %></p>

app/views/shared/_wikimedia_readiness.html.erb
<%# Local variables: @wr_data[Hash] %>

<h2>Wikimedia Readiness</h2>

<div class="description-text">
  <p>To be ready for upload into Wikimedia, items must have both of the following:</p>
  <br/>
  <p>
    <strong>Media access</strong> - either a IIIF manifest or 
    full-frame media file(s)
  </p>
  <p>
    <strong>Open rights</strong> - a standardized rights statement or 
    Creative Commons license compatible with the Wikimedia Commons copyright policy.
  </p>
  <br/>
</div>

<div class="metrics">

  <% if @wp_data.present? %>

    <table>

      <% @wp_data.each do |key, value| %>
        <% if WikimediaPreparationsPresenter.fields.include?(key) %>
          <tr>
            <td><%= key.titleize %></td>
            <td class="bar <%= percentage_class(value) %>">
              <%= render_percentage(value) %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>

  <% else %>
    <div class="no-data">Data not available</div>
  <% end %>

</div>