config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  namespace :admin do
    resources :users
  end

  resources :hubs, id: /.*/, only: [:index, :show] do
    get :website_overview
    get :api_overview
    get :bws_overview
    get :item_count
    get :metadata_completeness
    get :wikimedia_overview

    resources :contributors, id: /.*/, only: [:index, :show] do
      get :contributor_website_overview
      get :contributor_api_overview
      get :contributor_bws_overview
      get :contributor_item_count
      get :contributor_metadata_completeness
      get :contributor_wikimedia_overview
      resources :events, only: [:show]
      resources :locations, only: [:index]
      resources :timelines, only: [:show]
      resources :wikimedia_preparations, only: [:index]
    end
    resources :events, only: [:show]
    resources :locations, only: [:index]
    resources :timelines, only: [:show]
    resources :wikimedia_preparations, only: [:index]
  end

  resources :search_terms, only: [:show]

  get :api_events, controller: :events
  get :website_events, controller: :events
  get :bws_events, controller: :events
  get :api_search_terms, controller: :search_terms
  get :website_search_terms, controller: :search_terms
  get :contributor_comparison, controller: :contributors

  root 'hubs#index'
end

app/controllers/search_terms_controller.rb
# Handles HTTP requests for search terms

class SearchTermsController < ApplicationController
  # Controller concerns
  include DateSetter
  # View helpers
  include DataMenuHelper
  include DateHelper
  include SearchTermsHelper

  def show
    assign_start_and_end_dates
  end

  def website_search_terms
    assign_start_and_end_dates

    @search_terms = WebsiteSearchTerms.build do |builder|
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    respond_to do |format|
      format.html { render partial: "shared/search_terms_table"}
      format.csv { send_data @search_terms.to_csv }
    end
  end

  def api_search_terms
    assign_start_and_end_dates

    @search_terms = ApiSearchTerms.build do |builder|
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    respond_to do |format|
      format.html { render partial: "shared/search_terms_table"}
      format.csv { send_data @search_terms.to_csv }
    end
  end
end

app/helpers/search_terms_helper.rb
module SearchTermsHelper

  def scope_label
    params[:id] == "website" ? "Website" : "API"
  end

  ##
  # @param [Google::Apis::AnalyticsV3::GaData]
  # @return Integer
  def end_index(response)
    response.total_results.to_i < response.items_per_page.to_i ? 
      response.total_results : response.items_per_page
  end
end

app/views/search_terms/show.html.erb
<div class="heading">
  <h1>Search terms</h1>
  <%= render partial: "shared/date_menu" %>
</div>

<main>
  <div class="clear"/>

  <div class="data-menu">
    <ul>
      <li><%= render_website_terms_link %></li>
      <li><%= render_api_terms_link %></li>
    </ul>
  </div>

  <div class="data-content">
    <div class="data-section">
      <div class="item-table">

        <h2><%= scope_label %></h2>

        <div class="description-text">
          Top search terms across the DPLA <%= scope_label %> for all hubs and contributors.
          Equivalent to "search terms" in Google Analytics.
        </div>

        <% if params[:id] == "website" %>

          <%= render_async website_search_terms_path({ start_date: current_start_date,
                                                       end_date: current_end_date }),
                'data-turbolinks-track': 'reload' do %>
            <div>Loading...</div>
          <% end %>

        <% elsif params[:id] == "api" %>
           <%= render_async api_search_terms_path({ start_date: current_start_date,
                                                    end_date: current_end_date }),
                'data-turbolinks-track': 'reload' do %>
            <div>Loading...</div>
          <% end %>

        <% else %>
          The ID in the URI, "<%= params[:id] %>", is not recognized.
        <% end %>
      </div>
    </div>
  </div>
</main>