config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  namespace :admin do
    resources :users
  end

  resources :hubs, id: /.*/, only: [:index, :show] do
    get :website_overview
    get :api_overview
    get :bws_overview
    get :item_count
    get :metadata_completeness
    get :wikimedia_overview

    resources :contributors, id: /.*/, only: [:index, :show] do
      get :contributor_website_overview
      get :contributor_api_overview
      get :contributor_bws_overview
      get :contributor_item_count
      get :contributor_metadata_completeness
      get :contributor_wikimedia_overview
      resources :events, only: [:show]
      resources :locations, only: [:index]
      resources :timelines, only: [:show]
      resources :wikimedia_preparations, only: [:index]
    end
    resources :events, only: [:show]
    resources :locations, only: [:index]
    resources :timelines, only: [:show]
    resources :wikimedia_preparations, only: [:index]
  end

  resources :search_terms, only: [:show]

  get :api_events, controller: :events
  get :website_events, controller: :events
  get :bws_events, controller: :events
  get :api_search_terms, controller: :search_terms
  get :website_search_terms, controller: :search_terms
  get :contributor_comparison, controller: :contributors

  root 'hubs#index'
end

app/controllers/contributors_controller.rb
# Handles HTTP requests for contributors

class ContributorsController < ApplicationController
  # Controller concerns
  include DateSetter
  # View helpers
  include DataMenuHelper
  include DateHelper
  include MetadataCompletenessHelper
  include TooltipsHelper

  def index
    assign_start_and_end_dates
    @hub = Hub.new(params[:hub_id], @start_date, @end_date)

    unless current_user.hub == params[:hub_id] || current_user.hub == "All"
      redirect_to hub_contributors_path(current_user.hub)
    end
  end

  def show
    assign_start_and_end_dates
    @contributor = Contributor.new(params[:id],
                                   params[:hub_id],
                                   @start_date,
                                   @end_date)

    unless current_user.hub == params[:hub_id] || current_user.hub == "All"
      redirect_to hub_path(current_user.hub)
    end
  end

  def contributor_website_overview
    assign_start_and_end_dates

    @website_overview = WebsiteOverview.build do |builder|
      builder.hub = params[:hub_id]
      builder.contributor = params[:contributor_id]
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    @website_event_totals = WebsiteEventTotals.build do |builder|
      builder.hub = params[:hub_id]
      builder.contributor = params[:contributor_id]
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    render partial: "shared/frontend_use_metrics"
  end

  def contributor_api_overview
    assign_start_and_end_dates

    @api_overview = ApiOverview.build do |builder|
      builder.hub = params[:hub_id]
      builder.contributor = params[:contributor_id]
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    render partial: "shared/api_use_metrics"
  end

  def contributor_bws_overview
    assign_start_and_end_dates

    @bws_item_count = DplaApiResponseBuilder.new()
      .bws_item_count(params[:hub_id], params[:contributor_id])

    @bws_overview = BwsOverview.build do |builder|
      builder.hub = params[:hub_id]
      builder.contributor = params[:contributor_id]
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    @bws_event_totals = BwsEventTotals.build do |builder|
      builder.hub = params[:hub_id]
      builder.contributor = params[:contributor_id]
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    render partial: "shared/bws_use_metrics"
  end

  def contributor_item_count
    @item_count = DplaApiResponseBuilder.new()
      .item_count(params[:hub_id], params[:contributor_id])

    render partial: "shared/item_count"
  end

  def contributor_metadata_completeness
    assign_start_and_end_dates

    metadata_completeness = MetadataCompleteness.build do |builder|
      builder.hub = params[:hub_id]
      builder.contributor = params[:contributor_id]
      builder.end_date = @end_date
    end

    mc_presenter = MetadataCompletenessPresenter.new(metadata_completeness)
    @mc_data = mc_presenter.contributor(params[:hub_id], params[:contributor_id])
    render partial: "shared/metadata_completeness"
  end

  def contributor_wikimedia_overview
    assign_start_and_end_dates

    metadata_completeness = MetadataCompleteness.build do |builder|
      builder.hub = params[:hub_id]
      builder.contributor = params[:contributor_id]
      builder.end_date = @end_date
    end

    wp_presenter = WikimediaPreparationsPresenter.new(metadata_completeness)
    @wp_data = wp_presenter.contributor(params[:hub_id], params[:contributor_id])

    wikimedia_analytics = WikimediaAnalytics.build do |builder|
      builder.hub = params[:hub_id]
      builder.contributor = params[:contributor_id]
      builder.end_date = @end_date
    end

    wa_presenter = WikimediaAnalyticsPresenter.new(wikimedia_analytics)
    @wa_data = wa_presenter.contributor(params[:hub_id], params[:contributor_id])

    @target = Contributor.new(params[:contributor_id],
                              params[:hub_id],
                              @start_date,
                              @end_date)

    render partial: "shared/wikimedia_overview"
  end

  def contributor_comparison
    assign_start_and_end_dates
    
    contributors_item_count = DplaApiResponseBuilder.new
      .contributors_item_count(params[:hub_id])

    website_overview = WebsiteOverviewByContributor.build do |builder|
      builder.hub = params[:hub_id]
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    website_events = WebsiteEventsByContributor.build do |builder|
      builder.hub = params[:hub_id]
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    bws_item_count = DplaApiResponseBuilder.new
      .contributors_bws_item_count(params[:hub_id])

    bws_overview = BwsOverviewByContributor.build do |builder|
      builder.hub = params[:hub_id]
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    bws_events = BwsEventsByContributor.build do |builder|
      builder.hub = params[:hub_id]
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    api_overview = ApiOverviewByContributor.build do |builder|
      builder.hub = params[:hub_id]
      builder.start_date = @start_date
      builder.end_date = @end_date
    end

    metadata_completeness = MetadataCompleteness.build do |builder|
      builder.hub = params[:hub_id]
      builder.end_date = @end_date
    end

    wikimedia_analytics = WikimediaAnalytics.build do |builder|
      builder.hub = params[:hub_id]
      builder.contributor = params[:contributor_id]
      builder.end_date = @end_date
    end

    mc_presenter = MetadataCompletenessPresenter.new(metadata_completeness)
    wp_presenter = WikimediaPreparationsPresenter.new(metadata_completeness)
    wa_presenter = WikimediaAnalyticsPresenter.new(wikimedia_analytics)

    @contributor_comparison = ContributorComparison.build do |builder|
      builder.hub = params[:hub_id]
      builder.contributors_item_count = contributors_item_count
      builder.website_overview = website_overview
      builder.website_events = website_events
      builder.bws_item_count = bws_item_count
      builder.bws_overview = bws_overview
      builder.bws_events = bws_events
      builder.api_overview = api_overview
      builder.mc_presenter = mc_presenter
      builder.wp_presenter = wp_presenter
      builder.wa_presenter = wa_presenter
    end

    respond_to do |format|
      format.html { render partial: "shared/contributor_comparison" }
      format.csv { send_data @contributor_comparison.to_csv }
    end
  end
end

app/views/contributors/index.html.erb
<% content_for :head_script do %>
  <%= javascript_include_tag 'jquery-tablesorter.js',
      'data-turbo-track': 'reload', defer: 'defer' %>

  <%= javascript_include_tag 'tablesort', 
      'data-turbo-track': 'reload', defer: 'defer' %>
<% end %>

<%= render partial: "shared/sub_navigation", locals: { hub: @hub } %>

<script>
  function toggle_column(element) {
    els = document.getElementsByClassName(element.value);

    if (element.checked == true) {
      Array.prototype.forEach.call(els, function(el) {
        el.style.display="table-cell";
      });
    } else {
      Array.prototype.forEach.call(els, function(el) {
        el.style.display="none";
      });
    }
  }
</script>

<div class="heading">

  <h1><%= @hub.name %></h1>

  <%= render partial: "shared/date_menu" %>

</div>

<main>

  <div class="clear"/>

  <h2>Contributors</h2>

  <%= render_async contributor_comparison_path({ hub_id: params[:hub_id],
                                                 start_date: current_start_date,
                                                 end_date: current_end_date }),
        'data-turbolinks-track': 'reload',
        event_name: 'contributor-comparison-loaded' do %>
    <div>Loading...</div>
  <% end %>

</main>

app/views/contributors/show.html.erb
<%= render partial: "shared/sub_navigation",
  locals: { hub: @contributor.hub } %>

<% content_for :head_script do %>
  <%= javascript_include_tag 'google-analytics', 
    'data-turbo-track': 'reload', defer: 'defer' %>
<% end %>

<div class="heading">

  <h1><%= @contributor.name %></h1>

  <%= render partial: "shared/date_menu" %>

</div>

<main>

  <%= render partial: "shared/data_menu", locals: { target: @contributor } %>

  <div class="data-content">

    <div class="data-section">

      <div class="metrics">

        <div class="tooltip">
          <h2>DPLA Website (dp.la)</h2>
          <span class="tooltiptext"><%= website_use_tooltip %></span>
        </div>

        <%= render_async hub_contributor_contributor_website_overview_path(
              @contributor.hub.name, @contributor.name, date_opts),
              'data-turbolinks-track': 'reload' do %>
          <div>Loading...</div>
        <% end %>

        <br/>

        <div class="tooltip">
          <h2>Black Women's Suffrage</h2>
          <span class="tooltiptext"><%= bws_use_tooltip %></span>
        </div>

        <%= render_async hub_contributor_contributor_bws_overview_path(
          @contributor.hub.name, @contributor.name, date_opts),
              'data-turbolinks-track': 'reload' do %>
          <div>Loading...</div>
        <% end %>

      </div>

      <div class="metrics">

        <div class="tooltip">
          <h2>DPLA API</h2>
          <span class="tooltiptext"><%= api_use_tooltip %></span>
        </div>

        <%= render_async hub_contributor_contributor_api_overview_path(
              @contributor.hub.name, @contributor.name, date_opts),
              'data-turbolinks-track': 'reload' do %>
          <div>Loading...</div>
        <% end %>

        <br/>

        <div class="tooltip">
          <h2>Item Count</h2>
          <span class="tooltiptext"><%= item_count_tooltip %></span>
        </div>

        <%= render_async hub_contributor_contributor_item_count_path(
              @contributor.hub.name, @contributor.name, date_opts),
              'data-turbolinks-track': 'reload' do %>
          <div>Loading...</div>
        <% end %>

        <br/>

        <div class="tooltip">
          <h2>Wikimedia Integration</h2>
        </div>

        <%= render_async  hub_contributor_contributor_wikimedia_overview_path(
          @contributor.hub.name, @contributor.name, date_opts),
              'data-turbolinks-track': 'reload' do %>
          <div>Loading...</div>
        <% end %>
      </div>

      <div class="metrics">

        <div class="tooltip">
          <h2>Metadata Completeness</h2>
          <span class="tooltiptext"><%= metadata_completeness_tooltip %></span>
        </div>

        <%= render_async hub_contributor_contributor_metadata_completeness_path(
              @contributor.hub.name, @contributor.name, date_opts),
              'data-turbolinks-track': 'reload' do %>
          <div>Loading...</div>
        <% end %>

      </div>
    </div>
  </div>
</main>